### ISSUE TITLE
How are the lower, upper bounds and initial value of theta of kriging_theta_train() considered?

### ISSUE THREAD

**Issue by ariaisnotavailable** [zhandawei/Incremental_Kriging_Assisted_Evolutionary_Algorithm#1]
Firstly, thank you for all the help I've received from your paper and source code.

And when I'm training with my own dataset, I don't know how to set the upper and lower bounds of theta and the initial value to get a valid theta value.

I have come across the following conditions:
1. theta value is a set upper or lower bound;
2. theta value is a set initial value.

How should I set this? Looking forward and thank you very much for your reply.Best regards.

**Comment by zhandawei** [comment]
In this implementation, the best theta is searched within the lower bound and upper bound using matlab fmincon function in log10 scale. Therefore, it is better to set the search range as [10^a, 10^b]. From my experience, you can set the initial value as 10^0 = 1, and the lower and upper bound as [10^-6,10^6]. If you want to get a very good theta, then you can increase the iterations of fmincon function, i.e. in the optimoptions function increase the 'MaxFunctionEvaluations' value. Although I think this only bring very little improvement, you can give it a try.
